version: '3.8'

services:
  parking-app:
    image: node:lts-alpine
    container_name: test-solecode-app
    working_dir: /app
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    command: npm run start
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
    - db-mysql

  db-mysql:
    image: mysql/mysql-server:5.7
    container_name: test-solecode-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking_db
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
